/* ─────────────────────────────────────────────────────────────
   B2B panel data — transcribed from "B2B Panel Book 2026" (PDF)
   One entry per market page in the deck.
   ───────────────────────────────────────────────────────────── */

export interface Slice {
  label: string;
  pct: number;
}

export interface B2BMarket {
  id: string;
  label: string;
  code: string;
  /** Active panelists in this market */
  panelists: number;
  jobType: Slice[];       // Freelancer / Home-Based / Full time / Part time
  decisionMakers: { yes: number; no: number };
  workingClass: { blue: number; white: number };
  jobLevel: Slice[];      // Entry / Manager / Director / C-Level / Business Owners
  department: Slice[];
  industry: Slice[];
}

export const TOTAL_PANELISTS = 785500;

export const b2bMarkets: B2BMarket[] = [
  {
    id: "usa",
    label: "United States",
    code: "US",
    panelists: 60000,
    jobType: [
      { label: "Freelancer", pct: 10.66 },
      { label: "Home-Based", pct: 10.34 },
      { label: "Full time", pct: 64.55 },
      { label: "Part time", pct: 14.45 },
    ],
    decisionMakers: { yes: 68.10, no: 31.90 },
    workingClass: { blue: 8.48, white: 91.52 },
    jobLevel: [
      { label: "Entry Level", pct: 31.90 },
      { label: "Manager", pct: 38.97 },
      { label: "Director", pct: 11.93 },
      { label: "C-Level", pct: 6.95 },
      { label: "Business Owners", pct: 10.25 },
    ],
    department: [
      { label: "Others", pct: 20.28 },
      { label: "Administration", pct: 22.61 },
      { label: "Customer Support", pct: 15.14 },
      { label: "Finance", pct: 10.54 },
      { label: "Supply Chain/Procurement", pct: 10.30 },
      { label: "IT", pct: 7.57 },
      { label: "Human Resource", pct: 5.92 },
      { label: "Sales", pct: 5.06 },
      { label: "Marketing", pct: 2.58 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 7.65 },
      { label: "Social Work", pct: 1.79 },
      { label: "Education", pct: 10.00 },
      { label: "Manufacturing", pct: 4.00 },
      { label: "IT", pct: 9.14 },
      { label: "BFI", pct: 17.14 },
      { label: "Construction", pct: 9.50 },
      { label: "Federal", pct: 2.65 },
      { label: "Hospitality", pct: 2.78 },
      { label: "Automotive", pct: 4.25 },
      { label: "Aviation", pct: 0.91 },
      { label: "Tele-communication", pct: 1.35 },
      { label: "Agriculture", pct: 3.37 },
      { label: "Healthcare/Pharmaceutical", pct: 14.43 },
      { label: "Energy", pct: 0.88 },
      { label: "Others", pct: 10.15 },
    ],
  },
  {
    id: "canada",
    label: "Canada",
    code: "CA",
    panelists: 25000,
    jobType: [
      { label: "Freelancer", pct: 10.41 },
      { label: "Home-Based", pct: 6.64 },
      { label: "Full time", pct: 63.38 },
      { label: "Part time", pct: 19.57 },
    ],
    decisionMakers: { yes: 49.98, no: 50.02 },
    workingClass: { blue: 5.47, white: 94.53 },
    jobLevel: [
      { label: "Entry Level", pct: 50.02 },
      { label: "Manager", pct: 25.30 },
      { label: "Director", pct: 16.76 },
      { label: "C-Level", pct: 2.18 },
      { label: "Business Owners", pct: 5.75 },
    ],
    department: [
      { label: "Others", pct: 24.09 },
      { label: "Administration", pct: 20.09 },
      { label: "Customer Support", pct: 15.70 },
      { label: "Supply Chain/Procurement", pct: 9.47 },
      { label: "Finance", pct: 8.52 },
      { label: "Human Resource", pct: 8.52 },
      { label: "Marketing", pct: 5.47 },
      { label: "Sales", pct: 5.21 },
      { label: "IT", pct: 2.92 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 10.03 },
      { label: "Social Work", pct: 3.00 },
      { label: "Education", pct: 12.56 },
      { label: "Manufacturing", pct: 5.25 },
      { label: "IT", pct: 4.22 },
      { label: "BFI", pct: 8.94 },
      { label: "Construction", pct: 6.37 },
      { label: "Federal", pct: 7.22 },
      { label: "Hospitality", pct: 3.56 },
      { label: "Automotive", pct: 3.47 },
      { label: "Aviation", pct: 0.47 },
      { label: "Tele-communication", pct: 1.31 },
      { label: "Agriculture", pct: 1.97 },
      { label: "Healthcare/Pharmaceutical", pct: 16.21 },
      { label: "Energy", pct: 2.62 },
      { label: "Others", pct: 14.81 },
    ],
  },
  {
    id: "mexico",
    label: "Mexico",
    code: "MX",
    panelists: 19000,
    jobType: [
      { label: "Freelancer", pct: 18.22 },
      { label: "Home-Based", pct: 17.87 },
      { label: "Full time", pct: 47.00 },
      { label: "Part time", pct: 16.91 },
    ],
    decisionMakers: { yes: 67.27, no: 32.73 },
    workingClass: { blue: 6.25, white: 93.75 },
    jobLevel: [
      { label: "Entry Level", pct: 32.73 },
      { label: "Manager", pct: 25.21 },
      { label: "Director", pct: 36.67 },
      { label: "C-Level", pct: 2.02 },
      { label: "Business Owners", pct: 3.37 },
    ],
    department: [
      { label: "Others", pct: 24.30 },
      { label: "Administration", pct: 14.67 },
      { label: "Customer Support", pct: 13.78 },
      { label: "Marketing", pct: 11.85 },
      { label: "Human Resource", pct: 10.96 },
      { label: "Finance", pct: 10.84 },
      { label: "Supply Chain/Procurement", pct: 8.15 },
      { label: "Sales", pct: 3.81 },
      { label: "IT", pct: 1.64 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 3.61 },
      { label: "Social Work", pct: 0.38 },
      { label: "Education", pct: 9.74 },
      { label: "Manufacturing", pct: 4.90 },
      { label: "IT", pct: 3.52 },
      { label: "BFI", pct: 6.37 },
      { label: "Construction", pct: 8.03 },
      { label: "Federal", pct: 4.52 },
      { label: "Hospitality", pct: 3.33 },
      { label: "Automotive", pct: 9.65 },
      { label: "Aviation", pct: 2.09 },
      { label: "Tele-communication", pct: 1.81 },
      { label: "Agriculture", pct: 13.93 },
      { label: "Healthcare/Pharmaceutical", pct: 7.75 },
      { label: "Energy", pct: 1.43 },
      { label: "Others", pct: 18.96 },
    ],
  },
  {
    id: "uk",
    label: "UK",
    code: "GB",
    panelists: 45000,
    jobType: [
      { label: "Freelancer", pct: 6.65 },
      { label: "Home-Based", pct: 5.69 },
      { label: "Full time", pct: 63.21 },
      { label: "Part time", pct: 24.45 },
    ],
    decisionMakers: { yes: 52.62, no: 47.38 },
    workingClass: { blue: 3.04, white: 96.96 },
    jobLevel: [
      { label: "Entry Level", pct: 47.38 },
      { label: "Manager", pct: 25.59 },
      { label: "Director", pct: 18.23 },
      { label: "C-Level", pct: 2.76 },
      { label: "Business Owners", pct: 6.03 },
    ],
    department: [
      { label: "Others", pct: 26.04 },
      { label: "Administration", pct: 23.00 },
      { label: "Customer Support", pct: 11.94 },
      { label: "Finance", pct: 10.00 },
      { label: "Supply Chain/Procurement", pct: 7.83 },
      { label: "Human Resource", pct: 7.41 },
      { label: "Marketing", pct: 5.42 },
      { label: "Sales", pct: 4.67 },
      { label: "IT", pct: 3.67 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 8.51 },
      { label: "Social Work", pct: 1.85 },
      { label: "Education", pct: 14.90 },
      { label: "Manufacturing", pct: 4.03 },
      { label: "IT", pct: 6.74 },
      { label: "BFI", pct: 10.92 },
      { label: "Construction", pct: 5.58 },
      { label: "Federal", pct: 5.61 },
      { label: "Hospitality", pct: 4.96 },
      { label: "Automotive", pct: 4.01 },
      { label: "Aviation", pct: 1.00 },
      { label: "Tele-communication", pct: 1.18 },
      { label: "Agriculture", pct: 2.25 },
      { label: "Healthcare/Pharmaceutical", pct: 17.38 },
      { label: "Energy", pct: 1.00 },
      { label: "Others", pct: 10.09 },
    ],
  },
  {
    id: "uae",
    label: "UAE",
    code: "AE",
    panelists: 15000,
    jobType: [
      { label: "Freelancer", pct: 5.23 },
      { label: "Home-Based", pct: 9.38 },
      { label: "Full time", pct: 75.11 },
      { label: "Part time", pct: 10.28 },
    ],
    decisionMakers: { yes: 52.57, no: 47.43 },
    workingClass: { blue: 11.26, white: 88.74 },
    jobLevel: [
      { label: "Entry Level", pct: 47.38 },
      { label: "Manager", pct: 28.24 },
      { label: "Director", pct: 25.94 },
      { label: "C-Level", pct: 5.34 },
      { label: "Business Owners", pct: 6.72 },
    ],
    department: [
      { label: "Others", pct: 22.01 },
      { label: "Finance", pct: 13.04 },
      { label: "Sales", pct: 11.16 },
      { label: "Marketing", pct: 10.78 },
      { label: "IT", pct: 10.28 },
      { label: "Administration", pct: 9.34 },
      { label: "Human Resource", pct: 8.12 },
      { label: "Customer Support", pct: 8.02 },
      { label: "Supply Chain/Procurement", pct: 7.25 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 11.37 },
      { label: "Social Work", pct: 1.28 },
      { label: "Education", pct: 5.67 },
      { label: "Manufacturing", pct: 10.82 },
      { label: "IT", pct: 8.60 },
      { label: "BFI", pct: 6.24 },
      { label: "Construction", pct: 9.68 },
      { label: "Federal", pct: 3.22 },
      { label: "Hospitality", pct: 8.46 },
      { label: "Automotive", pct: 3.04 },
      { label: "Aviation", pct: 2.13 },
      { label: "Tele-communication", pct: 3.89 },
      { label: "Agriculture", pct: 2.26 },
      { label: "Healthcare/Pharmaceutical", pct: 5.54 },
      { label: "Energy", pct: 8.69 },
      { label: "Others", pct: 9.11 },
    ],
  },
  {
    id: "france",
    label: "France",
    code: "FR",
    panelists: 38000,
    jobType: [
      { label: "Freelancer", pct: 9.67 },
      { label: "Home-Based", pct: 6.74 },
      { label: "Full time", pct: 67.06 },
      { label: "Part time", pct: 16.53 },
    ],
    decisionMakers: { yes: 53.59, no: 46.41 },
    workingClass: { blue: 5.23, white: 94.77 },
    jobLevel: [
      { label: "Entry Level", pct: 46.41 },
      { label: "Manager", pct: 29.33 },
      { label: "Director", pct: 21.18 },
      { label: "C-Level", pct: 1.27 },
      { label: "Business Owners", pct: 1.82 },
    ],
    department: [
      { label: "Others", pct: 6.55 },
      { label: "Administration", pct: 3.15 },
      { label: "Customer Support", pct: 1.89 },
      { label: "Finance", pct: 3.34 },
      { label: "Supply Chain/Procurement", pct: 1.4 },
      { label: "IT", pct: 76.57 },
      { label: "Human Resource", pct: 2.77 },
      { label: "Sales", pct: 1.08 },
      { label: "Marketing", pct: 3.24 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 8.75 },
      { label: "Social Work", pct: 5.83 },
      { label: "Education", pct: 8.54 },
      { label: "Manufacturing", pct: 4.73 },
      { label: "IT", pct: 1.62 },
      { label: "BFI", pct: 2.83 },
      { label: "Construction", pct: 5.71 },
      { label: "Federal", pct: 14.64 },
      { label: "Hospitality", pct: 2.86 },
      { label: "Automotive", pct: 4.68 },
      { label: "Aviation", pct: 0.85 },
      { label: "Tele-communication", pct: 1.87 },
      { label: "Agriculture", pct: 3.72 },
      { label: "Healthcare/Pharmaceutical", pct: 13.05 },
      { label: "Energy", pct: 1.35 },
      { label: "Others", pct: 18.96 },
    ],
  },
  {
    id: "germany",
    label: "Germany",
    code: "DE",
    panelists: 42000,
    jobType: [
      { label: "Freelancer", pct: 7.41 },
      { label: "Home-Based", pct: 5.9 },
      { label: "Full time", pct: 64.86 },
      { label: "Part time", pct: 21.82 },
    ],
    decisionMakers: { yes: 42.49, no: 57.51 },
    workingClass: { blue: 5.77, white: 94.23 },
    jobLevel: [
      { label: "Entry Level", pct: 57.51 },
      { label: "Manager", pct: 20.31 },
      { label: "Director", pct: 16.16 },
      { label: "C-Level", pct: 2.53 },
      { label: "Business Owners", pct: 3.49 },
    ],
    department: [
      { label: "Others", pct: 29.06 },
      { label: "Administration", pct: 22.75 },
      { label: "Customer Support", pct: 10.23 },
      { label: "Finance", pct: 8.58 },
      { label: "Supply Chain/Procurement", pct: 10.63 },
      { label: "IT", pct: 3.5 },
      { label: "Human Resource", pct: 5.91 },
      { label: "Sales", pct: 4.89 },
      { label: "Marketing", pct: 4.46 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 11.53 },
      { label: "Social Work", pct: 1.95 },
      { label: "Education", pct: 7.6 },
      { label: "Manufacturing", pct: 4.92 },
      { label: "IT", pct: 4.29 },
      { label: "BFI", pct: 5.88 },
      { label: "Construction", pct: 5.55 },
      { label: "Federal", pct: 6.51 },
      { label: "Hospitality", pct: 3.37 },
      { label: "Automotive", pct: 5.83 },
      { label: "Aviation", pct: 0.35 },
      { label: "Tele-communication", pct: 1.24 },
      { label: "Agriculture", pct: 0.94 },
      { label: "Healthcare/Pharmaceutical", pct: 15.98 },
      { label: "Energy", pct: 1.62 },
      { label: "Others", pct: 23.14 },
    ],
  },
  {
    id: "italy",
    label: "Italy",
    code: "IT",
    panelists: 41500,
    jobType: [
      { label: "Freelancer", pct: 12.43 },
      { label: "Home-Based", pct: 11.61 },
      { label: "Full time", pct: 56.37 },
      { label: "Part time", pct: 19.59 },
    ],
    decisionMakers: { yes: 43.44, no: 56.56 },
    workingClass: { blue: 7.05, white: 92.95 },
    jobLevel: [
      { label: "Entry Level", pct: 56.56 },
      { label: "Manager", pct: 17.77 },
      { label: "Director", pct: 16.94 },
      { label: "C-Level", pct: 2.81 },
      { label: "Business Owners", pct: 5.91 },
    ],
    department: [
      { label: "Others", pct: 27.58 },
      { label: "Administration", pct: 19.09 },
      { label: "Customer Support", pct: 6.73 },
      { label: "Finance", pct: 10.33 },
      { label: "Supply Chain/Procurement", pct: 16.28 },
      { label: "IT", pct: 4.41 },
      { label: "Human Resource", pct: 5.89 },
      { label: "Sales", pct: 6.05 },
      { label: "Marketing", pct: 3.85 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 10.17 },
      { label: "Social Work", pct: 1.24 },
      { label: "Education", pct: 9.78 },
      { label: "Manufacturing", pct: 5.15 },
      { label: "IT", pct: 4.35 },
      { label: "BFI", pct: 6.09 },
      { label: "Construction", pct: 4.91 },
      { label: "Federal", pct: 5.42 },
      { label: "Hospitality", pct: 5.71 },
      { label: "Automotive", pct: 3.78 },
      { label: "Aviation", pct: 3.29 },
      { label: "Tele-communication", pct: 2.23 },
      { label: "Agriculture", pct: 4.78 },
      { label: "Healthcare/Pharmaceutical", pct: 10.02 },
      { label: "Energy", pct: 1.26 },
      { label: "Others", pct: 21.83 },
    ],
  },
  {
    id: "spain",
    label: "Spain",
    code: "ES",
    panelists: 26000,
    jobType: [
      { label: "Freelancer", pct: 9.71 },
      { label: "Home-Based", pct: 9.64 },
      { label: "Full time", pct: 58.6 },
      { label: "Part time", pct: 22.05 },
    ],
    decisionMakers: { yes: 56.59, no: 43.41 },
    workingClass: { blue: 4.93, white: 95.07 },
    jobLevel: [
      { label: "Entry Level", pct: 43.41 },
      { label: "Manager", pct: 17.26 },
      { label: "Director", pct: 33.31 },
      { label: "C-Level", pct: 4.45 },
      { label: "Business Owners", pct: 1.57 },
    ],
    department: [
      { label: "Others", pct: 30.76 },
      { label: "Administration", pct: 10.9 },
      { label: "Customer Support", pct: 17.66 },
      { label: "Finance", pct: 9.57 },
      { label: "Supply Chain/Procurement", pct: 8.86 },
      { label: "IT", pct: 2.09 },
      { label: "Human Resource", pct: 7.34 },
      { label: "Sales", pct: 3.41 },
      { label: "Marketing", pct: 9.41 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 3.59 },
      { label: "Social Work", pct: 0.84 },
      { label: "Education", pct: 12.13 },
      { label: "Manufacturing", pct: 5.07 },
      { label: "IT", pct: 2.94 },
      { label: "BFI", pct: 4.47 },
      { label: "Construction", pct: 6.32 },
      { label: "Federal", pct: 5.41 },
      { label: "Hospitality", pct: 11.46 },
      { label: "Automotive", pct: 3.88 },
      { label: "Aviation", pct: 1.2 },
      { label: "Tele-communication", pct: 2.49 },
      { label: "Agriculture", pct: 6.27 },
      { label: "Healthcare/Pharmaceutical", pct: 12.8 },
      { label: "Energy", pct: 1.6 },
      { label: "Others", pct: 19.6 },
    ],
  },
  {
    id: "india",
    label: "India",
    code: "IN",
    panelists: 75000,
    jobType: [
      { label: "Freelancer", pct: 14.72 },
      { label: "Home-Based", pct: 4.74 },
      { label: "Full time", pct: 62.07 },
      { label: "Part time", pct: 18.47 },
    ],
    decisionMakers: { yes: 81.03, no: 18.97 },
    workingClass: { blue: 6.63, white: 93.37 },
    jobLevel: [
      { label: "Entry Level", pct: 18.97 },
      { label: "Manager", pct: 45.24 },
      { label: "Director", pct: 23.03 },
      { label: "C-Level", pct: 5.37 },
      { label: "Business Owners", pct: 7.4 },
    ],
    department: [
      { label: "Others", pct: 11.52 },
      { label: "Administration", pct: 21.08 },
      { label: "Customer Support", pct: 6.67 },
      { label: "Finance", pct: 15.94 },
      { label: "Supply Chain/Procurement", pct: 5.08 },
      { label: "IT", pct: 15.22 },
      { label: "Human Resource", pct: 8.95 },
      { label: "Sales", pct: 6.44 },
      { label: "Marketing", pct: 9.1 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 3.67 },
      { label: "Social Work", pct: 1.81 },
      { label: "Education", pct: 15.9 },
      { label: "Manufacturing", pct: 4.01 },
      { label: "IT", pct: 17.21 },
      { label: "BFI", pct: 15.01 },
      { label: "Construction", pct: 2.68 },
      { label: "Federal", pct: 1.81 },
      { label: "Hospitality", pct: 1.65 },
      { label: "Automotive", pct: 6.4 },
      { label: "Aviation", pct: 2.02 },
      { label: "Tele-communication", pct: 2.31 },
      { label: "Agriculture", pct: 9.52 },
      { label: "Healthcare/Pharmaceutical", pct: 9.1 },
      { label: "Energy", pct: 0.79 },
      { label: "Others", pct: 6.11 },
    ],
  },
  {
    id: "australia",
    label: "Australia",
    code: "AU",
    panelists: 8500,
    jobType: [
      { label: "Freelancer", pct: 4.95 },
      { label: "Home-Based", pct: 4.78 },
      { label: "Full time", pct: 68.71 },
      { label: "Part time", pct: 21.56 },
    ],
    decisionMakers: { yes: 57.33, no: 42.67 },
    workingClass: { blue: 12.26, white: 87.74 },
    jobLevel: [
      { label: "Entry Level", pct: 42.67 },
      { label: "Manager", pct: 32.47 },
      { label: "Director", pct: 14.72 },
      { label: "C-Level", pct: 4.08 },
      { label: "Business Owners", pct: 6.07 },
    ],
    department: [
      { label: "Others", pct: 21.36 },
      { label: "Administration", pct: 25.86 },
      { label: "Customer Support", pct: 17.93 },
      { label: "Finance", pct: 7.57 },
      { label: "Supply Chain/Procurement", pct: 7.5 },
      { label: "IT", pct: 5.07 },
      { label: "Human Resource", pct: 5.71 },
      { label: "Sales", pct: 5.07 },
      { label: "Marketing", pct: 3.93 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 7.27 },
      { label: "Social Work", pct: 1.96 },
      { label: "Education", pct: 9.58 },
      { label: "Manufacturing", pct: 2.77 },
      { label: "IT", pct: 10.62 },
      { label: "BFI", pct: 18.36 },
      { label: "Construction", pct: 6.7 },
      { label: "Federal", pct: 3.59 },
      { label: "Hospitality", pct: 4.5 },
      { label: "Automotive", pct: 6.24 },
      { label: "Aviation", pct: 1.96 },
      { label: "Tele-communication", pct: 1.5 },
      { label: "Agriculture", pct: 5.77 },
      { label: "Healthcare/Pharmaceutical", pct: 9.7 },
      { label: "Energy", pct: 0.92 },
      { label: "Others", pct: 8.55 },
    ],
  },
  {
    id: "brazil",
    label: "Brazil",
    code: "BR",
    panelists: 29000,
    jobType: [
      { label: "Freelancer", pct: 23.15 },
      { label: "Home-Based", pct: 8.44 },
      { label: "Full time", pct: 57.13 },
      { label: "Part time", pct: 11.28 },
    ],
    decisionMakers: { yes: 65.02, no: 34.98 },
    workingClass: { blue: 9.27, white: 90.73 },
    jobLevel: [
      { label: "Entry Level", pct: 34.98 },
      { label: "Manager", pct: 34.22 },
      { label: "Director", pct: 20.32 },
      { label: "C-Level", pct: 2.18 },
      { label: "Business Owners", pct: 8.31 },
    ],
    department: [
      { label: "Others", pct: 21.54 },
      { label: "Administration", pct: 25.57 },
      { label: "Customer Support", pct: 13.12 },
      { label: "Finance", pct: 6.79 },
      { label: "Supply Chain/Procurement", pct: 8.15 },
      { label: "IT", pct: 6.95 },
      { label: "Human Resource", pct: 4.45 },
      { label: "Sales", pct: 6.86 },
      { label: "Marketing", pct: 6.58 },
    ],
    industry: [
      { label: "Wholesale/Retail", pct: 14.09 },
      { label: "Social Work", pct: 0.41 },
      { label: "Education", pct: 9.75 },
      { label: "Manufacturing", pct: 2.01 },
      { label: "IT", pct: 12.44 },
      { label: "BFI", pct: 6.44 },
      { label: "Construction", pct: 4.79 },
      { label: "Federal", pct: 4.94 },
      { label: "Hospitality", pct: 1.41 },
      { label: "Automotive", pct: 4.58 },
      { label: "Aviation", pct: 0.81 },
      { label: "Tele-communication", pct: 1.69 },
      { label: "Agriculture", pct: 5.2 },
      { label: "Healthcare/Pharmaceutical", pct: 10.05 },
      { label: "Energy", pct: 0.96 },
      { label: "Others", pct: 20.4 },
    ],
  },
];

/* ── Page-level content from the deck (not market-specific) ── */

export const recruitmentStrategy = [
  { label: "Professional network targeting", desc: "We conduct specialized outreach via LinkedIn and relevant industry forums" },
  { label: "Trusted referral system",         desc: "We leverage existing relationships within business networks" },
  { label: "Industry partnerships",           desc: "We collaborate with relevant and trusted professional organizations" },
  { label: "Continuous engagement",           desc: "We provide panelists with frequent updates and active participation monitoring" },
];

export const validationCriteria = [
  {
    title: "Industry Expertise",
    criteria: "Review of professional experience, publications, patents, or industry certifications",
    validation: "Panelists provide detailed information about their work experience and qualifications, verified through LinkedIn profiles and third-party B2B databases.",
  },
  {
    title: "Company / Position & Roles",
    criteria: "Panelists are associated with reputable and known companies within their industry",
    validation: "Panelists must provide their business email, LinkedIn profile, current role and job title. We verify this information using B2B databases, including ZoomInfo and Lusha.",
  },
  {
    title: "Geo Location",
    criteria: "Confirmed business location and address",
    validation: "Panelists are required to provide their location during registration. Additional IP geolocation tools are used to verify the location of panelists' internet connections.",
  },
  {
    title: "Engagement & Responsiveness",
    criteria: "Monitoring of response times, survey completion rates, and feedback from panelists",
    validation: "We track panelist response times and completion rates for surveys to assess their level of engagement, with post-survey questionnaires and direct communication used to gather insight into responsiveness and satisfaction.",
  },
  {
    title: "Data Quality & Consistency",
    criteria: "Regular assessment of response consistency, completion rates, and attention checks within surveys",
    validation: "We monitor panelist responses for consistency and completeness during survey administration. Attention checks verify attentiveness, and statistical analysis identifies outliers or patterns of inconsistent responses.",
  },
  {
    title: "Ethical Standards",
    criteria: "Monitoring for inappropriate behavior, adherence to research guidelines and codes of conduct",
    validation: "Clear guidelines and codes of conduct govern participation. Automated checks and random manual review detect ethical breaches, and panelists have channels for reporting concerns.",
  },
  {
    title: "Diversity",
    criteria: "A balance of industry sectors and demographics, including gender, ethnicity, company size, and geographic location",
    validation: "Panelists provide demographic information during registration. We audit panel composition regularly and take targeted recruitment action to address any imbalances.",
  },
];

export const fraudDetection = [
  { title: "Global Compliance: Data Privacy & Ethics", desc: "Ethical standards in line with international market research guidelines, ensuring strict compliance with GDPR, HIPAA, and ISO 27001." },
  { title: "Research Defender",       desc: "Advanced search and activity tools ensure the authenticity and reliability of research outcomes." },
  { title: "Survey Link Protection",  desc: "We proactively detect and prevent tampering with survey URLs, a common tactic used to bypass questions or improperly access incentives." },
  { title: "Digital Fingerprint Analysis", desc: "Examination of device type, browser version, operating system, and IP address generates a unique fingerprint that identifies duplicate or fraudulent entries." },
  { title: "CAPTCHA Integration",     desc: "CAPTCHA distinguishes between human and automated responses, preventing bots from submitting fraudulent entries." },
  { title: "Network Behavioral Analysis", desc: "Response timing, interaction patterns, and network anomalies are monitored to identify and prevent fraudulent behavior." },
  { title: "Server-to-Server (S2S) Integration", desc: "S2S integration securely exchanges data between servers, reducing the risk of data breaches." },
  { title: "Two-Factor Authentication (2FA)", desc: "2FA ensures that only authorized respondents can access and complete surveys." },
  { title: "IP Address Analysis",     desc: "IP addresses are monitored to detect and block multiple responses from the same location." },
  { title: "Geolocation Verification", desc: "We verify the geographic location of respondents, ensuring responses come from the locations we expect." },
];

export const panelAttributes = [
  {
    group: "Basic Attributes",
    items: ["Business Type", "Industry Segment", "Annual Revenue", "Number of Employees at all Locations", "Title", "Function/Department", "Decision Makers", "Job Category"],
  },
  {
    group: "Industry Segment Type",
    items: ["Computer Hardware", "Computer Software", "Consulting", "Consumer Products", "Consumer Services", "Entertainment/Sports", "Energies & Utilities/Oil & Gas", "Food/Beverages/Restaurants", "Media/Publishing/Advertising", "Non-Profit", "Retail", "Telecommunication", "Equipment", "Travel/Hospitality/Leisure", "E-commerce", "Beauty/Fashion", "Construction", "Finance + Insurance", "Automotive", "Aviation", "Manufacturing", "Healthcare", "Professional Services", "Real Estate", "Transport & Logistics", "Hospitality"],
  },
  {
    group: "Profession Targeting",
    items: ["Digital Marketers", "Insurance Agents", "Lawyers", "CPA", "Stylists", "Machinist", "Chemist/Scientist", "Graphic Designer", "Social Media", "Influencer", "Plumber", "Carpenter", "General Contractor", "Auto Mechanic", "Driver", "Electrician", "Factory/Warehouse Worker"],
  },
  {
    group: "Government / Military",
    items: ["Law Enforcement", "Military/Defence", "National Guard", "Medical", "Indian Foreign Service"],
  },
  {
    group: "ITDM / IT Roles",
    items: ["Developer", "Data Centre", "Cloud Computing", "Business Intelligence", "Big Data Analytics"],
  },
];
