/* ─────────────────────────────────────────────────────────────
   B2C panel data — generated from the live Track Opinion API
     GET https://trackapi.opinionest.com/CountryList
     GET https://trackapi.opinionest.com/api/Panel/PanelDetails?id={n}
   so these figures match trackopinion.com/online-panel exactly.

   Baked in as static data: re-run the generator to refresh after the
   source numbers change.
   ───────────────────────────────────────────────────────────── */

export interface Slice {
  label: string;
  pct: number;
}

export interface B2CMarket {
  id: string;
  label: string;
  code: string;
  /** Active panel users, pre-formatted e.g. "520,000" */
  users: string;
  female: number;
  male: number;
  /** Internet penetration, % */
  internetPenetration: number;
  age: Slice[];
  income: Slice[];
  education: Slice[];
}

export const b2cMarkets: B2CMarket[] = [
  {
    id: "australia",
    label: "Australia",
    code: "AU",
    users: "78,000",
    female: 70,
    male: 30,
    internetPenetration: 87,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 19 },
      { label: "25–34", pct: 40 },
      { label: "35–44", pct: 20 },
      { label: "45–54", pct: 5 },
      { label: "55–64", pct: 5 },
      { label: "65+", pct: 5 },
    ],
    income: [
      { label: "<$30K", pct: 17 },
      { label: "$30–69K", pct: 21 },
      { label: "$70–129K", pct: 31 },
      { label: "$130–250K", pct: 18 },
      { label: "$250K+", pct: 12 },
    ],
    education: [
      { label: "High school grade", pct: 4 },
      { label: "High school/Tertiary/Tech", pct: 4 },
      { label: "Bachelors degree", pct: 65 },
      { label: "Master degree", pct: 20 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 6 },
    ],
  },
  {
    id: "brazil",
    label: "Brazil",
    code: "BR",
    users: "196,000",
    female: 56,
    male: 44,
    internetPenetration: 75,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 5 },
      { label: "25–34", pct: 10 },
      { label: "35–44", pct: 28 },
      { label: "45–54", pct: 26 },
      { label: "55–64", pct: 21 },
      { label: "65+", pct: 21 },
    ],
    income: [
      { label: "<$4600", pct: 18 },
      { label: "$4600–49K", pct: 21 },
      { label: "$50–199K", pct: 21 },
      { label: "$200–500K", pct: 21 },
      { label: "$500K+", pct: 21 },
    ],
    education: [
      { label: "High school grade", pct: 2 },
      { label: "High school/Tertiary/Tech", pct: 22 },
      { label: "Bachelors degree", pct: 53 },
      { label: "Master degree", pct: 15 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 7 },
    ],
  },
  {
    id: "canada",
    label: "Canada",
    code: "CA",
    users: "154,000",
    female: 52,
    male: 48,
    internetPenetration: 94,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 9 },
      { label: "25–34", pct: 18 },
      { label: "35–44", pct: 22 },
      { label: "45–54", pct: 12 },
      { label: "55–64", pct: 18 },
      { label: "65+", pct: 18 },
    ],
    income: [
      { label: "<$25K", pct: 22 },
      { label: "$25–49K", pct: 22 },
      { label: "$50–99K", pct: 32 },
      { label: "$100–200K", pct: 20 },
      { label: "$200K+", pct: 4 },
    ],
    education: [
      { label: "High school grade", pct: 3 },
      { label: "High school/Tertiary/Tech", pct: 10 },
      { label: "Bachelors degree", pct: 52 },
      { label: "Master degree", pct: 30 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 5 },
    ],
  },
  {
    id: "china",
    label: "China",
    code: "CN",
    users: "157,000",
    female: 44,
    male: 56,
    internetPenetration: 74,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 31 },
      { label: "25–34", pct: 37 },
      { label: "35–44", pct: 25 },
      { label: "45–54", pct: 4 },
      { label: "55–64", pct: 2 },
      { label: "65+", pct: 2 },
    ],
    income: [
      { label: "<$30K", pct: 32 },
      { label: "$30–69K", pct: 7 },
      { label: "$70–119K", pct: 5 },
      { label: "$120–240K", pct: 32 },
      { label: "$240K+", pct: 24 },
    ],
    education: [
      { label: "High school grade", pct: 2 },
      { label: "High school/Tertiary/Tech", pct: 1 },
      { label: "Bachelors degree", pct: 40 },
      { label: "Master degree", pct: 36 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 21 },
    ],
  },
  {
    id: "france",
    label: "France",
    code: "FR",
    users: "165,000",
    female: 58,
    male: 42,
    internetPenetration: 93,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 17 },
      { label: "25–34", pct: 20 },
      { label: "35–44", pct: 19 },
      { label: "45–54", pct: 17 },
      { label: "55–64", pct: 14 },
      { label: "65+", pct: 14 },
    ],
    income: [
      { label: "<$20K", pct: 36 },
      { label: "$20–59K", pct: 27 },
      { label: "$60–119K", pct: 12 },
      { label: "$120–200K", pct: 12 },
      { label: "$200K+", pct: 12 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 14 },
      { label: "Bachelors degree", pct: 54 },
      { label: "Master degree", pct: 20 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 10 },
    ],
  },
  {
    id: "germany",
    label: "Germany",
    code: "DE",
    users: "180,000",
    female: 71,
    male: 29,
    internetPenetration: 92,
    age: [
      { label: "<17", pct: 2 },
      { label: "18–24", pct: 53 },
      { label: "25–34", pct: 27 },
      { label: "35–44", pct: 10 },
      { label: "45–54", pct: 3 },
      { label: "55–64", pct: 1 },
      { label: "65+", pct: 1 },
    ],
    income: [
      { label: "<$20K", pct: 34 },
      { label: "$20–59K", pct: 21 },
      { label: "$60–119K", pct: 18 },
      { label: "$120–400K", pct: 13 },
      { label: "$400K+", pct: 13 },
    ],
    education: [
      { label: "High school grade", pct: 3 },
      { label: "High school/Tertiary/Tech", pct: 15 },
      { label: "Bachelors degree", pct: 60 },
      { label: "Master degree", pct: 20 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "hong-kong",
    label: "Hong Kong",
    code: "HK",
    users: "85,000",
    female: 50,
    male: 50,
    internetPenetration: 94,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 7 },
      { label: "25–34", pct: 32 },
      { label: "35–44", pct: 34 },
      { label: "45–54", pct: 17 },
      { label: "55–64", pct: 7 },
      { label: "65+", pct: 7 },
    ],
    income: [
      { label: "<$100K", pct: 33 },
      { label: "$100–499K", pct: 30 },
      { label: "$500–999K", pct: 13 },
      { label: "$1–1.5Mn", pct: 14 },
      { label: "$1.5Mn+", pct: 10 },
    ],
    education: [
      { label: "High school grade", pct: 5 },
      { label: "High school/Tertiary/Tech", pct: 13 },
      { label: "Bachelors degree", pct: 63 },
      { label: "Master degree", pct: 17 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "india",
    label: "India",
    code: "IN",
    users: "520,000",
    female: 29,
    male: 71,
    internetPenetration: 46,
    age: [
      { label: "<17", pct: 8 },
      { label: "18–24", pct: 47 },
      { label: "25–34", pct: 20 },
      { label: "35–44", pct: 10 },
      { label: "45–54", pct: 6 },
      { label: "55–64", pct: 6 },
      { label: "65+", pct: 6 },
    ],
    income: [
      { label: "<$50K", pct: 35 },
      { label: "$50–79K", pct: 31 },
      { label: "$80–99K", pct: 14 },
      { label: "$100–150K", pct: 13 },
      { label: "$150K+", pct: 9 },
    ],
    education: [
      { label: "High school grade", pct: 18 },
      { label: "High school/Tertiary/Tech", pct: 38 },
      { label: "Bachelors degree", pct: 38 },
      { label: "Master degree", pct: 4 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "indonesia",
    label: "Indonesia",
    code: "ID",
    users: "320,000",
    female: 42,
    male: 58,
    internetPenetration: 73,
    age: [
      { label: "<17", pct: 3 },
      { label: "18–24", pct: 26 },
      { label: "25–34", pct: 35 },
      { label: "35–44", pct: 21 },
      { label: "45–54", pct: 8 },
      { label: "55–64", pct: 3 },
      { label: "65+", pct: 3 },
    ],
    income: [
      { label: "<$30Mn", pct: 64 },
      { label: "$30–59Mn", pct: 15 },
      { label: "$60–89Mn", pct: 10 },
      { label: "$90–200Mn", pct: 7 },
      { label: "$200Mn+", pct: 5 },
    ],
    education: [
      { label: "High school grade", pct: 3 },
      { label: "High school/Tertiary/Tech", pct: 14 },
      { label: "Bachelors degree", pct: 60 },
      { label: "Master degree", pct: 20 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 3 },
    ],
  },
  {
    id: "italy",
    label: "Italy",
    code: "IT",
    users: "162,000",
    female: 58,
    male: 42,
    internetPenetration: 88,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 17 },
      { label: "25–34", pct: 20 },
      { label: "35–44", pct: 19 },
      { label: "45–54", pct: 17 },
      { label: "55–64", pct: 14 },
      { label: "65+", pct: 14 },
    ],
    income: [
      { label: "<$20K", pct: 15 },
      { label: "$20–59K", pct: 53 },
      { label: "$60–99K", pct: 10 },
      { label: "$100–300K", pct: 12 },
      { label: "$300K+", pct: 9 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 8 },
      { label: "Bachelors degree", pct: 65 },
      { label: "Master degree", pct: 15 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 10 },
    ],
  },
  {
    id: "japan",
    label: "Japan",
    code: "JP",
    users: "250,000",
    female: 22,
    male: 78,
    internetPenetration: 94,
    age: [
      { label: "<17", pct: 2 },
      { label: "18–24", pct: 3 },
      { label: "25–34", pct: 8 },
      { label: "35–44", pct: 20 },
      { label: "45–54", pct: 35 },
      { label: "55–64", pct: 24 },
      { label: "65+", pct: 24 },
    ],
    income: [
      { label: "<$3Mn", pct: 38 },
      { label: "$3–6Mn", pct: 36 },
      { label: "$6–10Mn", pct: 20 },
      { label: "$10–20Mn", pct: 5 },
      { label: "$20Mn+", pct: 2 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 11 },
      { label: "Bachelors degree", pct: 48 },
      { label: "Master degree", pct: 20 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 19 },
    ],
  },
  {
    id: "korea",
    label: "Korea",
    code: "KR",
    users: "132,000",
    female: 52,
    male: 48,
    internetPenetration: 96,
    age: [
      { label: "<17", pct: 5 },
      { label: "18–24", pct: 3 },
      { label: "25–34", pct: 28 },
      { label: "35–44", pct: 30 },
      { label: "45–54", pct: 23 },
      { label: "55–64", pct: 9 },
      { label: "65+", pct: 9 },
    ],
    income: [
      { label: "<$20Mn", pct: 11 },
      { label: "$20–30Mn", pct: 13 },
      { label: "$30–50Mn", pct: 59 },
      { label: "$50–100Mn", pct: 3 },
      { label: "$100Mn+", pct: 14 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 1 },
      { label: "Bachelors degree", pct: 84 },
      { label: "Master degree", pct: 12 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 3 },
    ],
  },
  {
    id: "malaysia",
    label: "Malaysia",
    code: "MY",
    users: "145,000",
    female: 47,
    male: 53,
    internetPenetration: 90,
    age: [
      { label: "<17", pct: 4 },
      { label: "18–24", pct: 31 },
      { label: "25–34", pct: 26 },
      { label: "35–44", pct: 21 },
      { label: "45–54", pct: 10 },
      { label: "55–64", pct: 5 },
      { label: "65+", pct: 5 },
    ],
    income: [
      { label: "<$30K", pct: 27 },
      { label: "$30–59K", pct: 28 },
      { label: "$60–89K", pct: 19 },
      { label: "$90–150K", pct: 16 },
      { label: "$150K+", pct: 10 },
    ],
    education: [
      { label: "High school grade", pct: 36 },
      { label: "High school/Tertiary/Tech", pct: 31 },
      { label: "Bachelors degree", pct: 27 },
      { label: "Master degree", pct: 5 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 1 },
    ],
  },
  {
    id: "mexico",
    label: "Mexico",
    code: "MX",
    users: "125,000",
    female: 58,
    male: 42,
    internetPenetration: 76,
    age: [
      { label: "<17", pct: 6 },
      { label: "18–24", pct: 37 },
      { label: "25–34", pct: 32 },
      { label: "35–44", pct: 16 },
      { label: "45–54", pct: 6 },
      { label: "55–64", pct: 2 },
      { label: "65+", pct: 2 },
    ],
    income: [
      { label: "<$20K", pct: 45 },
      { label: "$20–99K", pct: 14 },
      { label: "$100–199K", pct: 14 },
      { label: "$200K–1Mn", pct: 14 },
      { label: "$1 Mn+", pct: 14 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 2 },
      { label: "Bachelors degree", pct: 56 },
      { label: "Master degree", pct: 35 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 7 },
    ],
  },
  {
    id: "new-zealand",
    label: "New Zealand",
    code: "NZ",
    users: "36,500",
    female: 74,
    male: 26,
    internetPenetration: 93,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 18 },
      { label: "25–34", pct: 25 },
      { label: "35–44", pct: 28 },
      { label: "45–54", pct: 12 },
      { label: "55–64", pct: 11 },
      { label: "65+", pct: 11 },
    ],
    income: [
      { label: "<$20K", pct: 11 },
      { label: "$20–49K", pct: 19 },
      { label: "$50–99K", pct: 40 },
      { label: "$100–150K", pct: 18 },
      { label: "$150K+", pct: 13 },
    ],
    education: [
      { label: "High school grade", pct: 4 },
      { label: "High school/Tertiary/Tech", pct: 10 },
      { label: "Bachelors degree", pct: 76 },
      { label: "Master degree", pct: 9 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 0 },
    ],
  },
  {
    id: "philippines",
    label: "Philippines",
    code: "PH",
    users: "210,000",
    female: 71,
    male: 29,
    internetPenetration: 73,
    age: [
      { label: "<17", pct: 2 },
      { label: "18–24", pct: 53 },
      { label: "25–34", pct: 27 },
      { label: "35–44", pct: 10 },
      { label: "45–54", pct: 3 },
      { label: "55–64", pct: 1 },
      { label: "65+", pct: 1 },
    ],
    income: [
      { label: "<$40K", pct: 60 },
      { label: "$40–99K", pct: 16 },
      { label: "$100–499K", pct: 17 },
      { label: "$500K–1Mn", pct: 4 },
      { label: "$1Mn+", pct: 2 },
    ],
    education: [
      { label: "High school grade", pct: 4 },
      { label: "High school/Tertiary/Tech", pct: 15 },
      { label: "Bachelors degree", pct: 54 },
      { label: "Master degree", pct: 25 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "poland",
    label: "Poland",
    code: "PL",
    users: "76,000",
    female: 68,
    male: 32,
    internetPenetration: 91,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 8 },
      { label: "25–34", pct: 29 },
      { label: "35–44", pct: 30 },
      { label: "45–54", pct: 17 },
      { label: "55–64", pct: 8 },
      { label: "65+", pct: 8 },
    ],
    income: [
      { label: "<$10K", pct: 66 },
      { label: "$10–39K", pct: 5 },
      { label: "$40–69K", pct: 10 },
      { label: "$70–100K", pct: 10 },
      { label: "$100K+", pct: 9 },
    ],
    education: [
      { label: "High school grade", pct: 7 },
      { label: "High school/Tertiary/Tech", pct: 2 },
      { label: "Bachelors degree", pct: 25 },
      { label: "Master degree", pct: 62 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 4 },
    ],
  },
  {
    id: "romania",
    label: "Romania",
    code: "RO",
    users: "128,000",
    female: 56,
    male: 44,
    internetPenetration: 85,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 15 },
      { label: "25–34", pct: 29 },
      { label: "35–44", pct: 33 },
      { label: "45–54", pct: 3 },
      { label: "55–64", pct: 14 },
      { label: "65+", pct: 14 },
    ],
    income: [
      { label: "<$2K", pct: 16 },
      { label: "$2–4K", pct: 25 },
      { label: "$4–5K", pct: 12 },
      { label: "$5–6K", pct: 17 },
      { label: "$6K+", pct: 30 },
    ],
    education: [
      { label: "High school grade", pct: 10 },
      { label: "High school/Tertiary/Tech", pct: 27 },
      { label: "Bachelors degree", pct: 40 },
      { label: "Master degree", pct: 21 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "singapore",
    label: "Singapore",
    code: "SG",
    users: "113,000",
    female: 49,
    male: 51,
    internetPenetration: 88,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 6 },
      { label: "25–34", pct: 28 },
      { label: "35–44", pct: 32 },
      { label: "45–54", pct: 21 },
      { label: "55–64", pct: 10 },
      { label: "65+", pct: 10 },
    ],
    income: [
      { label: "<$25K", pct: 28 },
      { label: "$25–49K", pct: 17 },
      { label: "$50–99K", pct: 18 },
      { label: "$100–200K", pct: 15 },
      { label: "$200K+", pct: 22 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 5 },
      { label: "Bachelors degree", pct: 79 },
      { label: "Master degree", pct: 13 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "spain",
    label: "Spain",
    code: "ES",
    users: "124,000",
    female: 57,
    male: 43,
    internetPenetration: 92,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 10 },
      { label: "25–34", pct: 16 },
      { label: "35–44", pct: 25 },
      { label: "45–54", pct: 24 },
      { label: "55–64", pct: 17 },
      { label: "65+", pct: 17 },
    ],
    income: [
      { label: "<$20K", pct: 29 },
      { label: "$20–59K", pct: 16 },
      { label: "$60–99K", pct: 26 },
      { label: "$100–500K", pct: 18 },
      { label: "$500K+", pct: 11 },
    ],
    education: [
      { label: "High school grade", pct: 4 },
      { label: "High school/Tertiary/Tech", pct: 28 },
      { label: "Bachelors degree", pct: 36 },
      { label: "Master degree", pct: 22 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 9 },
    ],
  },
  {
    id: "taiwan",
    label: "Taiwan",
    code: "TW",
    users: "144,000",
    female: 51,
    male: 49,
    internetPenetration: 93,
    age: [
      { label: "<17", pct: 3 },
      { label: "18–24", pct: 4 },
      { label: "25–34", pct: 25 },
      { label: "35–44", pct: 35 },
      { label: "45–54", pct: 23 },
      { label: "55–64", pct: 7 },
      { label: "65+", pct: 7 },
    ],
    income: [
      { label: "<$300K", pct: 20 },
      { label: "$300K–599K", pct: 15 },
      { label: "$600K–999K", pct: 19 },
      { label: "$1–2Mn", pct: 34 },
      { label: "$2Mn+", pct: 12 },
    ],
    education: [
      { label: "High school grade", pct: 2 },
      { label: "High school/Tertiary/Tech", pct: 8 },
      { label: "Bachelors degree", pct: 50 },
      { label: "Master degree", pct: 38 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
  {
    id: "thailand",
    label: "Thailand",
    code: "TH",
    users: "230,000",
    female: 46,
    male: 54,
    internetPenetration: 82,
    age: [
      { label: "<17", pct: 2 },
      { label: "18–24", pct: 9 },
      { label: "25–34", pct: 28 },
      { label: "35–44", pct: 32 },
      { label: "45–54", pct: 18 },
      { label: "55–64", pct: 9 },
      { label: "65+", pct: 9 },
    ],
    income: [
      { label: "<$200K", pct: 32 },
      { label: "$200–499K", pct: 43 },
      { label: "$500–999K", pct: 16 },
      { label: "$1–2Mn", pct: 6 },
      { label: "$2Mn+", pct: 3 },
    ],
    education: [
      { label: "High school grade", pct: 3 },
      { label: "High school/Tertiary/Tech", pct: 16 },
      { label: "Bachelors degree", pct: 57 },
      { label: "Master degree", pct: 20 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 4 },
    ],
  },
  {
    id: "uk",
    label: "UK",
    code: "GB",
    users: "320,000",
    female: 64,
    male: 36,
    internetPenetration: 95,
    age: [
      { label: "<17", pct: 2 },
      { label: "18–24", pct: 10 },
      { label: "25–34", pct: 27 },
      { label: "35–44", pct: 25 },
      { label: "45–54", pct: 11 },
      { label: "55–64", pct: 9 },
      { label: "65+", pct: 9 },
    ],
    income: [
      { label: "<$20K", pct: 27 },
      { label: "$20–39K", pct: 27 },
      { label: "$40–69K", pct: 30 },
      { label: "$70–90K", pct: 8 },
      { label: "$90K+", pct: 9 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 4 },
      { label: "Bachelors degree", pct: 50 },
      { label: "Master degree", pct: 39 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 5 },
    ],
  },
  {
    id: "usa",
    label: "USA",
    code: "US",
    users: "450,000",
    female: 54,
    male: 46,
    internetPenetration: 93,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 5 },
      { label: "25–34", pct: 42 },
      { label: "35–44", pct: 34 },
      { label: "45–54", pct: 6 },
      { label: "55–64", pct: 5 },
      { label: "65+", pct: 5 },
    ],
    income: [
      { label: "<$15K", pct: 32 },
      { label: "$15–29K", pct: 7 },
      { label: "$30–49K", pct: 5 },
      { label: "$50–100K", pct: 32 },
      { label: "$100K+", pct: 24 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 2 },
      { label: "Bachelors degree", pct: 47 },
      { label: "Master degree", pct: 42 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 8 },
    ],
  },
  {
    id: "vietnam",
    label: "Vietnam",
    code: "VN",
    users: "225,000",
    female: 52,
    male: 48,
    internetPenetration: 70,
    age: [
      { label: "<17", pct: 1 },
      { label: "18–24", pct: 23 },
      { label: "25–34", pct: 47 },
      { label: "35–44", pct: 21 },
      { label: "45–54", pct: 6 },
      { label: "55–64", pct: 2 },
      { label: "65+", pct: 2 },
    ],
    income: [
      { label: "<$20Mn", pct: 20 },
      { label: "$20–99Mn", pct: 29 },
      { label: "$100–199Mn", pct: 21 },
      { label: "$200–500Mn", pct: 22 },
      { label: "$500Mn+", pct: 8 },
    ],
    education: [
      { label: "High school grade", pct: 1 },
      { label: "High school/Tertiary/Tech", pct: 6 },
      { label: "Bachelors degree", pct: 68 },
      { label: "Master degree", pct: 24 },
      { label: "Doctoral or Professional degree(Ph.D,MD or similar)", pct: 2 },
    ],
  },
];
